version: "3"
services:
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    #    command: postgres -c shared_preload_libraries=pg_stat_statements
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: test

volumes:
  db-data: